//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApothecaryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int Id_продаж { get; set; }
        public System.DateTime Дата_продажи { get; set; }
        public int Id_товара { get; set; }
        public decimal Стоимость { get; set; }
        public int Количество { get; set; }
        public Nullable<decimal> Сумма_Продаж { get; set; }
    
        public virtual Список_Товаров Список_Товаров { get; set; }
    }
}
