//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApothecaryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расчет_с_поставщиками
    {
        public int Id_расчета { get; set; }
        public Nullable<System.DateTime> Дата_поставки { get; set; }
        public decimal Сумма_прибыли { get; set; }
        public int Id_поставщика { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
    }
}
