//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApothecaryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Список_Товаров
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Список_Товаров()
        {
            this.Продажи = new HashSet<Продажи>();
            this.Списание = new HashSet<Списание>();
        }
    
        public int Id_Товара { get; set; }
        public string Название_Товара { get; set; }
        public string Группа { get; set; }
        public System.DateTime Дата_Изготовления { get; set; }
        public System.DateTime Дата_Окончания_Срока_Годности { get; set; }
        public string Производитель { get; set; }
        public int Дозировка { get; set; }
        public int Id_поставщика { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Списание> Списание { get; set; }
    }
}
